### ISSUE TITLE
Gated build error (no connection string)

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-middleware-freertos#174]
We do not have more info as of now, but there is a concern that perhaps the gated build will fail if posting a PR from a fork.

```
2021-08-16T22:13:37.4992864Z ##[group]Running E2E tests
2021-08-16T22:13:37.4993336Z Installing node dependencies using npm
2021-08-16T22:13:38.7147333Z npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
2021-08-16T22:13:39.7467611Z npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
2021-08-16T22:13:39.9758969Z npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
2021-08-16T22:13:40.6765320Z npm WARN deprecated jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates
2021-08-16T22:13:41.4410469Z npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2021-08-16T22:13:41.6723764Z npm WARN deprecated har-validator@5.1.5: this library is no longer supported
2021-08-16T22:13:46.4613088Z 
2021-08-16T22:13:46.4615732Z > keytar@7.7.0 install /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/node_modules/keytar
2021-08-16T22:13:46.4617421Z > prebuild-install || npm run build
2021-08-16T22:13:46.4618016Z 
2021-08-16T22:13:46.5861931Z prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
2021-08-16T22:13:46.7902148Z npm ERR! code EACCES
2021-08-16T22:13:46.7904755Z npm ERR! syscall scandir
2021-08-16T22:13:46.7906455Z npm ERR! path /root/.npm/_logs
2021-08-16T22:13:46.7908992Z npm ERR! errno -13
2021-08-16T22:13:46.7920028Z npm ERR! 
2021-08-16T22:13:46.7921663Z npm ERR! Your cache folder contains root-owned files, due to a bug in
2021-08-16T22:13:46.7922787Z npm ERR! previous versions of npm which has since been addressed.
2021-08-16T22:13:46.7923798Z npm ERR! 
2021-08-16T22:13:46.7925338Z npm ERR! To permanently fix this problem, please run:
2021-08-16T22:13:46.7926258Z npm ERR!   sudo chown -R 1001:121 "/root/.npm"
2021-08-16T22:13:46.7940567Z glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
2021-08-16T22:13:46.7941404Z   errno: -13,
2021-08-16T22:13:46.7942513Z   code: 'EACCES',
2021-08-16T22:13:46.7943040Z   syscall: 'scandir',
2021-08-16T22:13:46.7943532Z   path: '/root/.npm/_logs'
2021-08-16T22:13:46.7943905Z }
2021-08-16T22:13:46.8073829Z 
2021-08-16T22:13:46.8075476Z > keytar@7.7.0 build /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/node_modules/keytar
2021-08-16T22:13:46.8076748Z > node-gyp rebuild
2021-08-16T22:13:46.8077125Z 
2021-08-16T22:13:47.4041497Z gyp WARN EACCES current user ("runner") does not have permission to access the dev dir "/root/.cache/node-gyp/14.17.4"
2021-08-16T22:13:47.4047191Z gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/node_modules/keytar/.node-gyp"
2021-08-16T22:13:48.0471775Z make: Entering directory '/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/node_modules/keytar/build'
2021-08-16T22:13:48.0491241Z   CXX(target) Release/obj.target/keytar/src/async.o
2021-08-16T22:13:49.1539254Z   CXX(target) Release/obj.target/keytar/src/main.o
2021-08-16T22:13:50.2159342Z   CXX(target) Release/obj.target/keytar/src/keytar_posix.o
2021-08-16T22:13:51.3466779Z   SOLINK_MODULE(target) Release/obj.target/keytar.node
2021-08-16T22:13:51.4147701Z   COPY Release/keytar.node
2021-08-16T22:13:51.4207930Z make: Leaving directory '/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/node_modules/keytar/build'
2021-08-16T22:13:51.5356417Z npm ERR! Callback called more than once.
2021-08-16T22:13:51.7869322Z npm notice created a lockfile as package-lock.json. You should commit this file.
2021-08-16T22:13:51.7925549Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
2021-08-16T22:13:51.7927045Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2021-08-16T22:13:51.7971492Z npm WARN ts-e2e@1.0.0 No description
2021-08-16T22:13:51.8015032Z npm WARN ts-e2e@1.0.0 No repository field.
2021-08-16T22:13:51.8039471Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@7.7.0 (node_modules/keytar):
2021-08-16T22:13:51.8041357Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@7.7.0 install: `prebuild-install || npm run build`
2021-08-16T22:13:51.8042457Z npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 243
2021-08-16T22:13:51.8043616Z 
2021-08-16T22:13:51.8063238Z added 329 packages from 327 contributors and audited 375 packages in 13.846s
2021-08-16T22:13:51.9003630Z 
2021-08-16T22:13:51.9004786Z 40 packages are looking for funding
2021-08-16T22:13:51.9005288Z   run `npm fund` for details
2021-08-16T22:13:51.9005559Z 
2021-08-16T22:13:51.9012028Z found 2 moderate severity vulnerabilities
2021-08-16T22:13:51.9012781Z   run `npm audit fix` to fix them, or `npm audit` for details
2021-08-16T22:13:51.9164118Z Done installing node dependencies
2021-08-16T22:13:51.9165091Z Compiling typescripts to js
2021-08-16T22:13:52.1062794Z 
2021-08-16T22:13:52.1065196Z > ts-e2e@1.0.0 build /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service
2021-08-16T22:13:52.1066303Z > tsc
2021-08-16T22:13:52.1066725Z 
2021-08-16T22:13:55.7790475Z Done compiling typescripts to js
2021-08-16T22:13:55.7791363Z Cleaning expired e2e resources
2021-08-16T22:13:55.9650512Z 
2021-08-16T22:13:55.9652985Z > ts-e2e@1.0.0 cleanup /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service
2021-08-16T22:13:55.9654712Z > node ./lib/common/e2e_test_cleanup.js --connectionString ${IOTHUB_CONNECTION_STRING} --e 5
2021-08-16T22:13:55.9655428Z 
2021-08-16T22:13:56.1882666Z ReferenceError: value is ''
2021-08-16T22:13:56.1885602Z     at Function.Registry.fromConnectionString (/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/node_modules/azure-iothub/dist/registry.js:1101:19)
2021-08-16T22:13:56.1888505Z     at /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:50:70
2021-08-16T22:13:56.1931914Z     at step (/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:38:23)
2021-08-16T22:13:56.1933937Z     at Object.next (/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:19:53)
2021-08-16T22:13:56.1935802Z     at /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:13:71
2021-08-16T22:13:56.1936834Z     at new Promise (<anonymous>)
2021-08-16T22:13:56.1938407Z     at __awaiter (/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:9:12)
2021-08-16T22:13:56.1940420Z     at iothubRegistryCleanup (/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:46:12)
2021-08-16T22:13:56.1942378Z     at /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:122:42
2021-08-16T22:13:56.1944205Z     at step (/home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service/lib/common/e2e_test_cleanup.js:38:23)
2021-08-16T22:13:56.2126693Z Done Cleaning expired e2e resources
2021-08-16T22:13:56.2127443Z Running tests
2021-08-16T22:13:56.3976574Z 
2021-08-16T22:13:56.3979022Z > ts-e2e@1.0.0 alltest /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service
2021-08-16T22:13:56.3980664Z > npm run iothub_e2e_test && npm run iothub_e2e_test_using_dm && npm run iot_provisioning_e2e_test && npm run iot_provisioning_e2e_test_using_dm
2021-08-16T22:13:56.3981435Z 
2021-08-16T22:13:56.5923991Z 
2021-08-16T22:13:56.5926549Z > ts-e2e@1.0.0 iothub_e2e_test /home/runner/work/azure-iot-middleware-freertos/azure-iot-middleware-freertos/tests/e2e/service
2021-08-16T22:13:56.5928428Z > mocha ./lib/iothub_client/e2e_iot_hub_client_test.js  --connectionString ${IOTHUB_CONNECTION_STRING} --e ${DEVICE_TEST_EXE} --timeout 120000
2021-08-16T22:13:56.5929635Z 
2021-08-16T22:13:57.0951020Z 
2021-08-16T22:13:57.0954405Z 
2021-08-16T22:13:57.0979764Z   1) "before all" hook: Initial test device and test child  process creation in "{root}"
2021-08-16T22:13:57.0984077Z 
2021-08-16T22:13:57.0985152Z   0 passing (4ms)
2021-08-16T22:13:57.0985593Z   1 failing
2021-08-16T22:13:57.0986129Z 
2021-08-16T22:13:57.0989367Z   1) "before all" hook: Initial test device and test child  process creation in "{root}":
2021-08-16T22:13:57.0990897Z      ReferenceError: value is ''
2021-08-16T22:13:57.0992487Z       at Function.Registry.fromConnectionString (node_modules/azure-iothub/dist/registry.js:1101:19)
2021-08-16T22:13:57.0993898Z       at createTestDevice (lib/common/e2e_test_core.js:89:35)
2021-08-16T22:13:57.0995172Z       at Object.createTestDeviceAndTestProcess (lib/common/e2e_test_core.js:374:5)
2021-08-16T22:13:57.0996507Z       at Context.testSetup (lib/iothub_client/e2e_iot_hub_client_test.js:59:20)
2021-08-16T22:13:57.0997507Z       at processImmediate (internal/timers.js:464:21)
2021-08-16T22:13:57.0998141Z 
2021-08-16T22:13:57.0998587Z 
2021-08-16T22:13:57.0999003Z 
2021-08-16T22:13:57.1094815Z npm ERR! code ELIFECYCLE
2021-08-16T22:13:57.1096406Z npm ERR! errno 1
2021-08-16T22:13:57.1131435Z npm ERR! ts-e2e@1.0.0 iothub_e2e_test: `mocha ./lib/iothub_client/e2e_iot_hub_client_test.js  --connectionString ${IOTHUB_CONNECTION_STRING} --e ${DEVICE_TEST_EXE} --timeout 120000`
2021-08-16T22:13:57.1134673Z npm ERR! Exit status 1
2021-08-16T22:13:57.1135039Z npm ERR! 
2021-08-16T22:13:57.1135687Z npm ERR! Failed at the ts-e2e@1.0.0 iothub_e2e_test script.
2021-08-16T22:13:57.1136432Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-08-16T22:13:57.1165819Z 
2021-08-16T22:13:57.1166292Z npm ERR! A complete log of this run can be found in:
2021-08-16T22:13:57.1167116Z npm ERR!     /root/.npm/_logs/2021-08-16T22_13_57_113Z-debug.log
2021-08-16T22:13:57.1235888Z npm ERR! code ELIFECYCLE
2021-08-16T22:13:57.1236310Z npm ERR! errno 1
2021-08-16T22:13:57.1274270Z npm ERR! ts-e2e@1.0.0 alltest: `npm run iothub_e2e_test && npm run iothub_e2e_test_using_dm && npm run iot_provisioning_e2e_test && npm run iot_provisioning_e2e_test_using_dm`
2021-08-16T22:13:57.1275069Z npm ERR! Exit status 1
2021-08-16T22:13:57.1275420Z npm ERR! 
2021-08-16T22:13:57.1275990Z npm ERR! Failed at the ts-e2e@1.0.0 alltest script.
2021-08-16T22:13:57.1276704Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-08-16T22:13:57.1301706Z 
2021-08-16T22:13:57.1302980Z npm ERR! A complete log of this run can be found in:
2021-08-16T22:13:57.1303857Z npm ERR!     /root/.npm/_logs/2021-08-16T22_13_57_127Z-debug.log
2021-08-16T22:13:57.1350533Z ##[error]Process completed with exit code 1.
2021-08-16T22:13:57.1437628Z Post job cleanup.
2021-08-16T22:13:57.2376400Z [command]/usr/bin/git version
2021-08-16T22:13:57.2417944Z git version 2.32.0
2021-08-16T22:13:57.2452041Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-08-16T22:13:57.2484586Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-08-16T22:13:57.2684483Z Entering 'libraries/azure-sdk-for-c'
2021-08-16T22:13:57.2721720Z Entering 'libraries/coreMQTT'
2021-08-16T22:13:57.2765899Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-08-16T22:13:57.2788356Z http.https://github.com/.extraheader
2021-08-16T22:13:57.2796632Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-08-16T22:13:57.2825872Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-08-16T22:13:57.3023671Z Entering 'libraries/azure-sdk-for-c'
2021-08-16T22:13:57.3060749Z Entering 'libraries/coreMQTT'
2021-08-16T22:13:57.3156625Z Cleaning up orphan processes
```

**Comment by hihigupt** [comment]
This looks to be more like issue related to access for github Secretes.

Following log show issue not able to fetch connection string:

"before all" hook: Initial test device and test child  process creation in "{root}":
2021-08-16T22:13:57.0990897Z      ReferenceError: value is ''
2021-08-16T22:13:57.0992487Z       at Function.Registry.fromConnectionString (node_modules/azure-iothub/dist/registry.js:1101:19)
2021-08-16T22:13:57.0993898Z       at createTestDevice (lib/common/e2e_test_core.js:89:35)
2021-08-16T22:13:57.0995172Z       at Object.createTestDeviceAndTestProcess (lib/common/e2e_test_core.js:374:5)
2021-08-16T22:13:57.0996507Z       at Context.testSetup (lib/iothub_client/e2e_iot_hub_client_test.js:59:20)
2021-08-16T22:13:57.0997507Z       at processImmediate (internal/timers.js:464:21)

**Comment by ewertons** [comment]
Possible reference link: https://github.community/t/make-secrets-available-to-builds-of-forks/16166
